{
 "title": "Dashboard for node-app",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Node pod memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"default\", container=\"node-app\", pod=~\"node-app.*\"} / 1048576"
    }
   ]
  },
  {
   "title": "http responses labeled with: status_code 200",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{job=\"node-app\", method=\"GET\", path=\"/\", status_code=\"200\"}"
    }
   ]
  },
  {
   "title": "Percentage of request shortest than 0.5 second",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_request_duration_seconds_bucket{job=\"node-app\", le=\"0.5\"}[1d])) / sum (increase(http_request_duration_seconds_count{job=\"node-app\"}[1d]))) * 100"
    }
   ]
  },
  {
   "title": "Request Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m])) * 60"
    }
   ]
  }
 ]
}