replicaCount: 1

image:
  repository: nickvab/node_app
  pullPolicy: IfNotPresent
  tag: "2.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: 
  runAsUser: 1000
  runAsGroup: 1000
  privileged: false
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL

service:
  type: NodePort
  port: 8080
  protocol: TCP
  targetPort: 8080
  nodePort: 30001

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

budget:
  minAvailable: 2

  #resources:
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi
  #  limits:
  #    cpu: 200m
  #    memory: 256Mi

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: node-app.k8s.sandbox
      paths:
        - path: /
          pathType: ImplementationSpecific

nodeSelector: {}

tolerations: []

affinity: {}
