{{- if .Values.budget.minAvailable -}}
apiVersion: policy/v1  
kind: PodDisruptionBudget  
metadata:  
  name: {{ include "node-app.fullname" . }}  
spec:
  minAvailable: {{ .Values.budget.minAvailable }}
  selector:  
    matchLabels:  
    app: {{ include "node-app.name" . }} 
{{- end -}}
